"""Initial migration reflecting current models

Revision ID: 05363b6133a6
Revises: 
Create Date: 2026-07-05 20:08:15.737163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05363b6133a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.alter_column('lobby_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.alter_column('lobby_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
